In [1]:
import pandas as pd
import quandl
import math

Code | Details |
---- | ------- |
UENV/WNFI_IDN	| Net Freshwater Supplied by Water Supply Industry in Indonesia |
UENV/XMWC_IDN |	Municipal Waste Collected in Indonesia |
UENV/WGFA_IDN |	Gross Freshwater Abstracted in Indonesia |
BP/C02_EMMISSIONS_IDN | BP CO_2 Emission from BP |

In [8]:
df_wnfi = quandl.get('UENV/WNFI_IDN')
df_xmwc = quandl.get('UENV/XMWC_IDN')
df_wgfa = quandl.get('UENV/WGFA_IDN')
df_bpco2 = quandl.get('BP/C02_EMMISSIONS_IDN')

In [9]:
df_bpco2.head(5)

                Value
Date
1965-12-31  20.140746
1966-12-31  19.548792
1967-12-31  18.687913
1968-12-31  19.614088
1969-12-31  21.292424

In [11]:
df_el_idn = quandl.get('UENG/EL_IDN')

In [12]:
df_el_idn

,"Electricity - Gross production (Kilowatt-hours, million)","From combustible fuels – Main activity (Kilowatt-hours, million)","From combustible fuels – Main activity – Electricity plants (Kilowatt-hours, million)","Hydro – Main activity (Kilowatt-hours, million)","From combustible fuels – Autoproducer (Kilowatt-hours, million)","From combustible fuels – Autoproducer – Electricity plants (Kilowatt-hours, million)","Hydro – Autoproducer (Kilowatt-hours, million)","Electricity - net production (Kilowatt-hours, million)","Electricity - imports (Kilowatt-hours, million)","Electricity - Own use by electricity, heat and CHP plants (Kilowatt-hours, million)",...,"Geothermal – Main activity (Kilowatt-hours, million)","Geothermal – Main activity – Electricity plants (Kilowatt-hours, million)","Solar – Autoproducer (Kilowatt-hours, million)","Solar photovoltaic – Autoproducer (Kilowatt-hours, million)","Electricity - Consumption by non-metallic minerals (Kilowatt-hours, million)","Wind – Autoproducer (Kilowatt-hours, million)","From other sources – Main activity (Kilowatt-hours, million)","From other sources – Main activity – Electricity plants (Kilowatt-hours, million)","Geothermal – Autoproducer (Kilowatt-hours, million)","Geothermal – Autoproducer – Electricity plants (Kilowatt-hours, million)"
Date,,,,,,,,,,,,,,,,,,,,,
1990-12-31,48897.00,27432.0,NaN,5890.0,10100.0,NaN,4350.00,47225.00,NaN,1672.00,...,1125.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-12-31,51452.00,30026.0,NaN,5974.0,10200.0,NaN,4150.00,49885.00,NaN,1567.00,...,1102.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992-12-31,54940.00,30843.0,NaN,8572.0,10300.0,NaN,4200.00,52989.00,NaN,1951.00,...,1025.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993-12-31,58888.00,35316.0,NaN,7835.0,10400.0,NaN,4250.00,56917.00,NaN,1971.00,...,1087.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994-12-31,64351.00,41072.0,NaN,6878.0,10500.0,NaN,4300.00,62360.00,NaN,1991.00,...,1601.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995-12-31,68399.00,44676.0,NaN,6563.0,10600.0,NaN,4350.00,66138.00,NaN,2261.00,...,2210.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996-12-31,78117.00,53936.0,NaN,6868.0,10702.0,NaN,4401.00,75529.00,NaN,2588.00,...,2210.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997-12-31,84096.00,61093.0,NaN,5306.0,10805.0,NaN,4453.00,80866.00,NaN,3230.00,...,2439.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998-12-31,76017.00,62747.0,NaN,10580.0,65.0,NaN,32.00,72798.00,NaN,3219.00,...,2593.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-31,95944.00,68006.0,NaN,9364.0,11289.0,NaN,4557.00,94917.00,NaN,1027.00,...,2728.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-12-31,99511.00,71744.0,NaN,9110.0,11397.0,NaN,4611.00,98456.00,NaN,1055.00,...,2649.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-12-31,101647.00,83876.0,NaN,11595.0,84.0,NaN,61.00,97937.00,NaN,3710.00,...,6031.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-12-31,108206.00,91807.0,NaN,9848.0,221.0,NaN,92.00,104546.00,NaN,3660.00,...,6238.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-12-31,112944.00,97259.0,NaN,8970.0,289.0,NaN,111.00,108904.00,NaN,4040.00,...,6315.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-12-31,120160.00,103132.0,NaN,9636.0,704.0,NaN,37.00,114336.00,NaN,5824.00,...,6651.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-12-31,127369.00,109679.0,NaN,10718.0,327.0,NaN,41.00,122067.00,NaN,5302.00,...,6604.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-12-31,133108.00,116454.0,NaN,9582.0,373.0,NaN,41.00,127567.00,NaN,5541.00,...,6658.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-12-31,142236.00,123432.0,123432.0,11245.0,497.0,497.0,41.00,136315.00,NaN,5921.00,...,7021.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-12-31,149437.00,129002.0,129002.0,10740.0,610.0,610.0,788.00,144057.00,NaN,5380.00,...,8297.00,8297.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-12-31,157516.05,136119.0,136119.0,10307.0,714.0,714.0,1077.00,152292.05,1.26,5224.00,...,9295.00,9295.00,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
2010-12-31,169569.52,125944.0,125944.0,15827.0,16808.0,16808.0,1629.00,163297.00,2.22,6272.52,...,9357.00,9357.00,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
2011-12-31,182389.00,128934.0,128934.0,10316.0,31659.0,31659.0,2103.00,175502.00,2.54,6887.00,...,9371.00,9371.00,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN
2012-12-31,196180.90,135670.0,135670.0,10525.0,38287.0,38287.0,2274.00,190390.00,2.44,5790.90,...,9417.00,9417.00,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN
2013-12-31,222017.40,146602.0,146602.0,13014.0,45988.5,45988.5,2696.00,211175.00,2.99,10842.40,...,9414.00,9414.00,NaN,NaN,NaN,1.4,218.00,218.00,4078.0,4078.0
2014-12-31,234549.10,150478.0,150478.0,14816.0,49515.3,49515.3,3984.00,224537.00,8.99,10012.10,...,9996.00,9996.00,NaN,NaN,29172.0,NaN,NaN,NaN,5753.0,5753.0
2015-12-31,267287.08,142227.0,142227.0,10004.5,98471.0,98471.0,7590.00,254449.00,12.75,12838.08,...,4391.55,4391.55,NaN,NaN,NaN,NaN,398.75,398.75,4199.0,4199.0
2016-12-31,233367.44,148606.0,148606.0,13885.0,52603.0,52603.0,7590.44,223455.44,1.00,9912.00,...,3958.00,3958.00,12.0,12.0,NaN,6.0,0.00,0.00,6698.0,6698.0
2017-12-31,283647.10,207769.1,207769.1,12425.1,43996.7,43996.7,6207.30,269579.00,1119.50,14068.10,...,4096.00,4096.00,23.2,23.2,NaN,6.0,450.00,450.00,8667.9,8667.9
2018-12-31,293202.90,243889.3,243889.3,19774.0,16322.0,16322.0,NaN,273793.00,NaN,19409.90,...,12804.00,12804.00,NaN,NaN,NaN,NaN,407.00,407.00,NaN,NaN